name: moula
description: "A Money Tracker App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  go_router: ^14.2.0
  riverpod_annotation: ^2.3.5
  collection: ^1.18.0
  flutter_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/

